# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c3d44a2f859a953b49422de70d89ac757bf97c77dced76b4ca24b6612aca536ba1af8dc1db8d79579845212e339b77aab2b06b25e29c34c7a684794d71df2bf6

test:
  secret_key_base: 64ea9a9acd15105b92add2ce48374ac9dc5f17a7437f05e3a5e0a89e4e242eb1da87985f73844d45882b985c81880127f8ed6232a9b266f51441330770fb12f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
